#!/usr/bin/env php
<?php

chdir(dirname($argv[0]).'/..');

include("includes/defaults.inc.php");
include("config.php");
include("includes/definitions.inc.php");
include("includes/functions.php");

$osmap = array(
  "arista" => "arista",
  "avocent" => "avocent",
  "f5" => "f5",
  "fortigate" => "fortigate",
  "ftos" => "force10",
  "ios" => "cisco",
  "iosxe" => "cisco",
  "iosxr" => "cisco-xr",
  "ironware" => "foundry",
  "hp" => "hp",
  "junos" => "juniper",
  "nxos" => "cisco-nx",
  "routeros" => "mikrotik",
  "screenos" => "netscreen"
);

?>
# do not edit file directly!
#RANCID router.db autogenerated by <?php echo $_SERVER['SCRIPT_FILENAME']; ?>

<?php

foreach (dbFetchRows("SELECT hostname, os FROM `devices` WHERE `ignore` = 0 AND `disabled` = 0 ORDER BY hostname") as $device)
{
  foreach ( $osmap as $observiumos => $rancidos ) {
    if ( $device['os'] == $observiumos ) {
      echo($device['hostname'] . ":" . $rancidos . ":up" . PHP_EOL);
    }
  }
}

// EOF
